import { useEffect, useState } from 'react';
import { History, MessageCircle, Save, Search, Settings, Users } from 'lucide-react';
import type { User } from '../types';
import { authHeaders } from '../utils/auth';

type Contact={studentId:string;studentName:string;nisn:string;classId:string;guardian1Name:string;guardian1Phone:string;guardian1Masked?:string;guardian1Enabled:boolean;guardian2Name:string;guardian2Phone:string;guardian2Masked?:string;guardian2Enabled:boolean;consentAt?:string};
type Teacher={teacherId:string;teacherName:string;identifier:string;phone:string;masked?:string;enabled:boolean;reminderTime:string};
type HistoryRow={id:string;recipient_phone:string;message_type:string;status:string;attempt_count:number;scheduled_at:string;sent_at?:string;last_error?:string;delivery_state?:string};
type DailyStat={stat_date:string;queued:number;sent:number;failed:number;skipped:number};
type GatewayStatus={status:'never_seen'|'online'|'stale';reportedStatus:string;lastSeen?:string;version?:string;health?:{ready?:boolean;inFlight?:number;lastError?:string}};
type HistoryPage={hasMore:boolean;nextCursor:string|null;nextCursorId:string|null};

async function requestJson(url:string,options?:RequestInit):Promise<any>{
  const response=await fetch(url,options);
  let body:any;
  try{body=await response.json();}catch{throw new Error(`Respons server tidak valid (${response.status}).`);}
  if(!response.ok||body.success===false)throw new Error(body.error||`Request gagal (${response.status}).`);
  return body;
}

export function WhatsAppAdminSection({currentUser}:{currentUser:User}){
  const [tab,setTab]=useState<'wali'|'guru'|'riwayat'|'pengaturan'>('wali');
  const [contacts,setContacts]=useState<Contact[]>([]);const[teachers,setTeachers]=useState<Teacher[]>([]);const[history,setHistory]=useState<HistoryRow[]>([]);const[historyPage,setHistoryPage]=useState<HistoryPage|null>(null);const[historyLoading,setHistoryLoading]=useState(false);const[stats,setStats]=useState<DailyStat[]>([]);const[gateway,setGateway]=useState<GatewayStatus|null>(null);
  const[search,setSearch]=useState('');const[msg,setMsg]=useState('');const[isError,setIsError]=useState(false);
  const[settings,setSettings]=useState<any>({enabled:0,integration_enabled:0,emergency_pause:1,rollout_mode:'off',allowlist_json:'[]',absence_cutoff:'09:00',active_start:'05:00',active_end:'17:00',max_batch:25,retention_days:30});
  const isSuper=currentUser.role==='super_admin';
  const load=async()=>{try{const[cj,tj,hj,sj]=await Promise.all(['/api/whatsapp/contacts','/api/whatsapp/teachers','/api/whatsapp/history?limit=50','/api/whatsapp/settings'].map(url=>requestJson(url,{headers:authHeaders()})));setContacts(cj.data||[]);setTeachers(tj.data||[]);setHistory(hj.data||[]);setHistoryPage(hj.page||null);setStats(sj.stats||[]);setGateway(sj.gateway||null);if(sj.data)setSettings(sj.data);setIsError(false);}catch(error){setIsError(true);setMsg(error instanceof Error?error.message:'Gagal memuat data WhatsApp.');}};
  useEffect(()=>{load();},[]);// eslint-disable-line react-hooks/exhaustive-deps
  const save=async(url:string,body:unknown,successMessage:string)=>{try{await requestJson(url,{method:'PUT',headers:authHeaders({'Content-Type':'application/json'}),body:JSON.stringify(body)});setIsError(false);setMsg(successMessage);await load();}catch(error){setIsError(true);setMsg(error instanceof Error?error.message:'Gagal menyimpan.');}};
  const saveContact=(c:Contact)=>save('/api/whatsapp/contacts',{...c,consent:!!c.consentAt||c.guardian1Enabled||c.guardian2Enabled},'Kontak wali berhasil disimpan.');
  const saveTeacher=(t:Teacher)=>save('/api/whatsapp/teachers',t,'Pengingat guru berhasil disimpan.');
  const saveSettings=()=>{let allowlist:unknown;try{allowlist=JSON.parse(settings.allowlist_json||'[]');}catch{setIsError(true);setMsg('Allowlist harus berupa JSON array yang valid.');return;}save('/api/whatsapp/settings',{enabled:Number(settings.enabled)===1,integrationEnabled:Number(settings.integration_enabled)===1,emergencyPause:Number(settings.emergency_pause)===1,rolloutMode:settings.rollout_mode,allowlist,absenceCutoff:settings.absence_cutoff,activeStart:settings.active_start,activeEnd:settings.active_end,maxBatch:settings.max_batch,retentionDays:settings.retention_days},'Pengaturan berhasil disimpan.');};
  const loadMoreHistory=async()=>{if(!historyPage?.hasMore||!historyPage.nextCursor||historyLoading)return;setHistoryLoading(true);try{const query=new URLSearchParams({limit:'50',cursor:historyPage.nextCursor,cursorId:historyPage.nextCursorId||''});const result=await requestJson(`/api/whatsapp/history?${query}`,{headers:authHeaders()});setHistory(current=>[...current,...(result.data||[])]);setHistoryPage(result.page||null);}catch(error){setIsError(true);setMsg(error instanceof Error?error.message:'Gagal memuat riwayat lanjutan.');}finally{setHistoryLoading(false);}};
  const historyAction=async(body:unknown,successMessage:string)=>{try{await requestJson('/api/whatsapp/history',{method:'POST',headers:authHeaders({'Content-Type':'application/json'}),body:JSON.stringify(body)});setIsError(false);setMsg(successMessage);await load();}catch(error){setIsError(true);setMsg(error instanceof Error?error.message:'Operasi riwayat gagal.');}};
  const reconcile=async(row:HistoryRow,resolution:'sent'|'failed')=>{const note=window.prompt(resolution==='sent'?'Bukti/verifikasi bahwa pesan sudah terkirim:':'Alasan memastikan pesan tidak perlu dikirim ulang:');if(!note)return;await historyAction({action:'reconcile',id:row.id,resolution,note},'Status tidak pasti berhasil direkonsiliasi.');};
  const filtered=contacts.filter(c=>`${c.studentName} ${c.nisn} ${c.classId}`.toLowerCase().includes(search.toLowerCase()));
  return <div className="mx-auto max-w-7xl space-y-6 px-4 py-8 sm:px-6 lg:px-8">
    <div className="rounded-3xl bg-gradient-to-r from-emerald-900 to-slate-900 p-6 text-white sm:p-8"><div className="flex items-center gap-3"><MessageCircle className="h-8 w-8 text-emerald-400"/><div><h1 className="text-2xl font-extrabold">WhatsApp Sekolah</h1><p className="text-xs text-slate-300">Kontak wali, reminder guru, dan antrean hemat kuota.</p></div></div></div>
    {msg&&<p role={isError?'alert':'status'} className={`rounded-xl p-3 text-sm font-bold ${isError?'bg-rose-50 text-rose-700':'bg-emerald-50 text-emerald-700'}`}>{msg}</p>}
    <div className="grid grid-cols-2 gap-2 rounded-2xl bg-white p-2 border border-slate-200 sm:grid-cols-4">{([{id:'wali',label:'Kontak Wali',icon:Users},{id:'guru',label:'Reminder Guru',icon:MessageCircle},{id:'riwayat',label:'Riwayat',icon:History},{id:'pengaturan',label:'Pengaturan',icon:Settings}] as const).map(x=><button key={x.id} onClick={()=>setTab(x.id)} className={`flex items-center justify-center gap-2 rounded-xl px-2 py-2.5 text-xs font-bold cursor-pointer ${tab===x.id?'bg-slate-900 text-white':'bg-slate-50 text-slate-600'}`}><x.icon className="h-4 w-4"/>{x.label}</button>)}</div>
    {tab==='wali'&&<div className="space-y-4"><div className="relative"><Search className="absolute left-3 top-3 h-4 w-4 text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Cari siswa, NISN, atau kelas" className="w-full rounded-xl border border-slate-200 py-2.5 pl-9 pr-3 text-sm"/></div>{filtered.map((c,i)=><div key={c.studentId} className="space-y-4 rounded-2xl border border-slate-200 bg-white p-4 sm:p-5"><div><strong className="text-sm">{c.studentName}</strong><p className="text-xs text-slate-500">{c.nisn} · {c.classId}</p></div><div className="grid gap-3 md:grid-cols-2">{[1,2].map(slot=>{const nameKey=`guardian${slot}Name` as keyof Contact,phoneKey=`guardian${slot}Phone` as keyof Contact,enabledKey=`guardian${slot}Enabled` as keyof Contact;return <div key={slot} className="space-y-2 rounded-xl bg-slate-50 p-3"><label className="text-xs font-bold">Wali {slot}</label><input placeholder="Nama wali" value={String(c[nameKey]||'')} onChange={e=>{const n=[...contacts];(n[contacts.indexOf(c)] as any)[nameKey]=e.target.value;setContacts(n)}} className="w-full rounded-lg border p-2 text-sm"/><input placeholder="08xxxxxxxxxx" value={String(c[phoneKey]||'')} onChange={e=>{const n=[...contacts];(n[contacts.indexOf(c)] as any)[phoneKey]=e.target.value;setContacts(n)}} className="w-full rounded-lg border p-2 text-sm"/><label className="flex items-center gap-2 text-xs"><input type="checkbox" checked={Boolean(c[enabledKey])} onChange={e=>{const n=[...contacts];(n[contacts.indexOf(c)] as any)[enabledKey]=e.target.checked;setContacts(n)}}/>Aktif dan wali menyetujui notifikasi</label></div>})}</div><button onClick={()=>saveContact(c)} className="flex items-center gap-2 rounded-xl bg-emerald-600 px-4 py-2.5 text-xs font-bold text-white cursor-pointer"><Save className="h-4 w-4"/>Simpan Kontak</button></div>)}</div>}
    {tab==='guru'&&<div className="grid gap-3">{teachers.map(t=><div key={t.teacherId} className="grid gap-3 rounded-2xl border border-slate-200 bg-white p-4 md:grid-cols-[1fr_220px_120px_auto] md:items-center"><div><strong className="text-sm">{t.teacherName}</strong><p className="text-xs text-slate-500">{t.identifier}</p></div><input value={t.phone} onChange={e=>setTeachers(v=>v.map(x=>x.teacherId===t.teacherId?{...x,phone:e.target.value}:x))} placeholder="08xxxxxxxxxx" className="min-w-0 rounded-xl border p-2.5 text-sm"/><input type="time" value={t.reminderTime} onChange={e=>setTeachers(v=>v.map(x=>x.teacherId===t.teacherId?{...x,reminderTime:e.target.value}:x))} className="rounded-xl border p-2.5 text-sm"/><div className="flex items-center gap-2"><label className="text-xs"><input type="checkbox" checked={t.enabled} onChange={e=>setTeachers(v=>v.map(x=>x.teacherId===t.teacherId?{...x,enabled:e.target.checked}:x))}/> Aktif</label><button onClick={()=>saveTeacher(t)} className="rounded-lg bg-emerald-600 p-2 text-white cursor-pointer"><Save className="h-4 w-4"/></button></div></div>)}</div>}
    {tab==='riwayat'&&<div className="grid gap-2">{history.map(h=><div key={h.id} className="min-w-0 rounded-xl border border-slate-200 bg-white p-4 text-xs"><div className="flex flex-wrap justify-between gap-2"><strong>{h.message_type}</strong><span className="rounded-full bg-slate-100 px-2 py-0.5 font-bold">{h.status}</span></div><p className="mt-1 break-words text-slate-500">{h.recipient_phone} · {h.scheduled_at}</p>{h.last_error&&<p className="mt-1 text-rose-600">{h.last_error}</p>}{h.status==='sent_unknown'&&isSuper&&<div className="mt-3 flex flex-wrap gap-2"><button onClick={()=>reconcile(h,'sent')} className="rounded-lg bg-emerald-600 px-3 py-1.5 font-bold text-white">Konfirmasi terkirim</button><button onClick={()=>reconcile(h,'failed')} className="rounded-lg bg-rose-600 px-3 py-1.5 font-bold text-white">Tutup sebagai gagal</button></div>}</div>)}{historyPage?.hasMore&&<button disabled={historyLoading} onClick={loadMoreHistory} className="rounded-xl border border-slate-300 bg-white px-4 py-2.5 text-xs font-bold disabled:opacity-50">{historyLoading?'Memuat...':'Muat lebih banyak'}</button>}</div>}
    {tab==='pengaturan'&&<div className="space-y-3 rounded-2xl border border-slate-200 bg-slate-50 p-5"><div className="flex flex-wrap items-center justify-between gap-2"><div><strong className="text-sm">Status operasional gateway</strong><p className="text-xs text-slate-500">Last seen: {gateway?.lastSeen?new Date(gateway.lastSeen).toLocaleString('id-ID'):'belum pernah'}</p></div><span className={`rounded-full px-3 py-1 text-xs font-bold ${gateway?.status==='online'?'bg-emerald-100 text-emerald-700':gateway?.status==='stale'?'bg-amber-100 text-amber-700':'bg-slate-200 text-slate-600'}`}>{gateway?.status||'never_seen'} · {gateway?.reportedStatus||'unknown'}</span></div>{gateway?.health?.lastError&&<p className="rounded-lg bg-rose-50 p-2 text-xs text-rose-700">{gateway.health.lastError}</p>}<div className="grid gap-3 sm:grid-cols-2"><label className="flex items-center gap-2 text-xs font-bold"><input type="checkbox" disabled={!isSuper} checked={Number(settings.integration_enabled)===1} onChange={e=>setSettings({...settings,integration_enabled:e.target.checked?1:0})}/>Izinkan integrasi eksternal</label><label className="flex items-center gap-2 text-xs font-bold text-rose-700"><input type="checkbox" disabled={!isSuper} checked={Number(settings.emergency_pause)===1} onChange={e=>setSettings({...settings,emergency_pause:e.target.checked?1:0})}/>Emergency pause</label><label className="text-xs font-bold">Rollout<select disabled={!isSuper} value={settings.rollout_mode} onChange={e=>setSettings({...settings,rollout_mode:e.target.value})} className="mt-1 w-full rounded-xl border bg-white p-2.5"><option value="off">Off</option><option value="canary">Canary</option><option value="all">Semua</option></select></label><label className="text-xs font-bold">Allowlist canary (JSON)<textarea disabled={!isSuper} value={settings.allowlist_json} onChange={e=>setSettings({...settings,allowlist_json:e.target.value})} rows={2} className="mt-1 w-full rounded-xl border bg-white p-2.5 font-mono"/></label></div><p className="text-xs text-slate-500">Tiga pengaman harus dibuka: integrasi, pengiriman otomatis, dan rollout. Emergency pause harus mati.</p></div>}
    {tab==='pengaturan'&&<div className="space-y-4 rounded-2xl border border-slate-200 bg-white p-5"><p className="text-xs text-slate-500">Gateway menggunakan WhatsApp Web pada komputer sekolah. Hanya Super Admin dapat mengubah konfigurasi.</p><label className="flex items-center gap-2 text-sm font-bold"><input type="checkbox" disabled={!isSuper} checked={Number(settings.enabled)===1} onChange={e=>setSettings({...settings,enabled:e.target.checked?1:0})}/>Aktifkan pengiriman otomatis</label><div className="grid gap-3 sm:grid-cols-2"><label className="text-xs font-bold">Batas kirim Alpa<input type="time" disabled={!isSuper} value={settings.absence_cutoff} onChange={e=>setSettings({...settings,absence_cutoff:e.target.value})} className="mt-1 w-full rounded-xl border p-2.5"/></label><label className="text-xs font-bold">Retensi riwayat (hari)<input type="number" min="7" max="90" disabled={!isSuper} value={settings.retention_days} onChange={e=>setSettings({...settings,retention_days:e.target.value})} className="mt-1 w-full rounded-xl border p-2.5"/></label><label className="text-xs font-bold">Jam aktif mulai<input type="time" disabled={!isSuper} value={settings.active_start} onChange={e=>setSettings({...settings,active_start:e.target.value})} className="mt-1 w-full rounded-xl border p-2.5"/></label><label className="text-xs font-bold">Jam aktif selesai<input type="time" disabled={!isSuper} value={settings.active_end} onChange={e=>setSettings({...settings,active_end:e.target.value})} className="mt-1 w-full rounded-xl border p-2.5"/></label></div>{stats.length>0&&<div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead><tr className="text-slate-500"><th className="py-2">Tanggal</th><th>Antre</th><th>Terkirim</th><th>Gagal</th><th>Dilewati</th></tr></thead><tbody>{stats.map(stat=><tr key={stat.stat_date} className="border-t"><td className="py-2">{stat.stat_date}</td><td>{stat.queued}</td><td>{stat.sent}</td><td>{stat.failed}</td><td>{stat.skipped}</td></tr>)}</tbody></table></div>}{isSuper&&<button onClick={saveSettings} className="rounded-xl bg-slate-900 px-4 py-3 text-sm font-bold text-white cursor-pointer">Simpan Pengaturan</button>}</div>}
  </div>;
}
